"use client";

import { ChangeEvent, DragEvent, startTransition, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Download, Heart, ImagePlus, PawPrint, Sparkles, Upload, UserRound, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Stage = "home" | "samples" | "choose" | "photos" | "details" | "mood" | "theme" | "add" | "companion" | "generating" | "reveal" | "confirmation";
type Product = "me" | "pet" | "partner" | "family";
const lines = ["Studying the little\ndetails…", "Sketching your tiny\nuniverse…", "Adding main-character\nenergy…", "Cutting the perfect\nborders…"];
const positions = ["0% 0%", "50% 0%", "100% 0%", "0% 34%", "50% 34%", "100% 34%", "0% 68%", "50% 68%", "100% 68%", "50% 100%"];
const samples = ["01","02","03","04","05","06"];
const moodOptions = ["Cute","Funny","Cozy","Chaotic","Dreamy","Cool","Sweet","Playful"];
const genericStickerIcons = [PawPrint, Heart, Sparkles, UserRound, PawPrint, Heart, Sparkles, UserRound, PawPrint, Heart];

function Sheet({ name, className = "", clean = false, src = "/sticker-sheet.png" }: { name: string; className?: string; clean?: boolean; src?: string }) {
  return <div className={`sheet ${className} ${clean?"clean-sheet":""}`}>{!clean&&<div className="sheet-head"><b>{name.toUpperCase()}&apos;S ERA</b><span>01 / 01</span></div>}<img src={src} alt={`${name}'s custom sticker sheet`} />{!clean&&<div className="sheet-foot">ONE OF ONE · MADE FOR YOU ✦</div>}</div>;
}
function Progress({ n, total }: { n: number; total: number }) {
  return <div className="wizard-progress"><span>STEP {String(n).padStart(2,"0")} / {String(total).padStart(2,"0")}</span><div><i style={{width:`${n/total*100}%`}}/></div></div>;
}
function UploadBox({ previews, pet, target = "yourself", onChange }: { previews:string[]; pet:boolean; target?:string; onChange:(f:FileList|null)=>void }) {
  const drop=(e:DragEvent<HTMLLabelElement>)=>{e.preventDefault();e.currentTarget.classList.remove("dragging");onChange(e.dataTransfer.files)};
  return <label className="upload-zone" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("dragging")}} onDragLeave={e=>e.currentTarget.classList.remove("dragging")} onDrop={drop}><input type="file" accept="image/*" multiple onChange={(e:ChangeEvent<HTMLInputElement>)=>onChange(e.target.files)}/><div className="upload-icon">{pet?<PawPrint/>:<ImagePlus/>}</div><b>{previews.length?`${previews.length} PHOTO${previews.length>1?"S":""} ADDED`:"DROP YOUR PHOTOS HERE"}</b><p>{previews.length?"Looking good. Drop or choose more if you want.":`Drag photos here, or click below · Add 3–6 clear photos of ${target}`}</p><span><Upload size={15}/> CHOOSE PHOTOS</span>{previews.length>0&&<div className="preview-row">{previews.slice(0,5).map((s,i)=><img src={s} alt={`Upload ${i+1}`} key={i}/>)}</div>}</label>;
}
function GenericStickerSheet() {
  return <div className="generic-sticker-sheet">{genericStickerIcons.map((Icon,index)=><div className={`generic-sticker generic-sticker-${index%4}`} key={index}><Icon/></div>)}</div>;
}

export default function Home(){
  const [stage,setStage]=useState<Stage>("home");
  const [product,setProduct]=useState<Product>("me");
  const [name,setName]=useState("Theresa");
  const [groupName,setGroupName]=useState("");
  const [photos,setPhotos]=useState<string[]>([]);
  const [companionPhotos,setCompanionPhotos]=useState<string[]>([]);
  const [companion,setCompanion]=useState<"pet"|"person"|"skip">("skip");
  const [specialRequest,setSpecialRequest]=useState("");
  const [pet,setPet]=useState({name:"Mochi",species:"Dog"});
  const [theme,setTheme]=useState("Classic");
  const [moods,setMoods]=useState<string[]>([]);
  const [paymentOpen,setPaymentOpen]=useState(false);
  const [paymentPlan,setPaymentPlan]=useState<"one-time"|"subscription">("one-time");
  const [paymentStep,setPaymentStep]=useState<"email"|"payment">("email");
  const [email,setEmail]=useState("");
  const [checkoutError,setCheckoutError]=useState("");
  const [checkoutLoading,setCheckoutLoading]=useState(false);
  const [subscriptionLoading,setSubscriptionLoading]=useState(false);
  const [checkoutSessionId,setCheckoutSessionId]=useState("");
  const [generatedImage,setGeneratedImage]=useState("");
  const [generatedImageKey,setGeneratedImageKey]=useState("");
  const [generatedSlices,setGeneratedSlices]=useState<string[]>([]);
  const [generationError,setGenerationError]=useState("");
  const [tick,setTick]=useState(0);
  const subject=product==="pet"?(pet.name||"Your pet"):product==="partner"?(groupName||"My partner"):product==="family"?(groupName||"Family & friends"):(name||"You");
  const total=product==="me"?7:5;
  const photoTarget=product==="pet"?"your pet":product==="partner"?"you and your partner":product==="family"?"your family and friends":"yourself";
  const themeLabel=theme.toUpperCase();
  const requestExample=product==="pet"?"Favorite toy, signature accessory, funny habit, nickname, or anything else that feels like them.":product==="partner"?"Example: Include flowers.":product==="family"?"Example: Include matching outfits or an inside joke.":"Example: Add a tote bag and a tiny cup of matcha.";
  const currentStep=({choose:1,photos:2,details:3,mood:4,theme:5,add:6,companion:7} as Partial<Record<Stage,number>>)[stage]||1;
  useEffect(()=>{if(stage!=="generating")return;const a=window.setInterval(()=>setTick(x=>(x+1)%4),2200);return()=>clearInterval(a)},[stage]);
  useEffect(()=>{if(!generatedImage)return;const image=new Image();image.onload=()=>{const slices:string[]=[];for(let index=0;index<10;index++){const column=index===9?1:index%3;const row=Math.floor(index/3);const canvas=document.createElement("canvas");canvas.width=image.naturalWidth/3;canvas.height=image.naturalHeight/4;canvas.getContext("2d")?.drawImage(image,column*canvas.width,row*canvas.height,canvas.width,canvas.height,0,0,canvas.width,canvas.height);slices.push(canvas.toDataURL("image/png"))}setGeneratedSlices(slices)};image.src=generatedImage},[generatedImage]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const checkout=params.get("checkout");const sessionId=params.get("session_id");const checkoutEmail=params.get("email");if(checkout||sessionId)startTransition(()=>{if(checkout==="success")setStage("confirmation");if(sessionId)setCheckoutSessionId(sessionId);if(checkoutEmail)setEmail(checkoutEmail)});if(checkout){window.history.replaceState({},"",window.location.pathname)}},[]);
  useEffect(()=>{if(["choose","photos","details","mood","theme","add","companion"].includes(stage))window.scrollTo({top:0,left:0,behavior:"auto"})},[stage]);
  const load=async(files:FileList|null,setter:(x:string[])=>void)=>{if(!files)return;const urls=await Promise.all(Array.from(files).slice(0,6).map(file=>new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file)})));setter(urls)};
  const start=(p:Product)=>{setProduct(p);setPhotos([]);setMoods([]);setGeneratedImage("");setGeneratedImageKey("");setGeneratedSlices([]);setStage("photos")};
  const generate=async()=>{setTick(0);setGenerationError("");setStage("generating");try{const referencePhotos=product==="pet"?photos:[...photos,...companionPhotos];const response=await fetch("/api/generate-stickers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({photos:referencePhotos,subject,product,companion,companionName:companion==="pet"?pet.name:groupName,species:pet.species,theme,moods,specialRequest})});const data=await response.json() as {imageUrl?:string;imageKey?:string;error?:string};if(!response.ok||!data.imageUrl||!data.imageKey)throw new Error(data.error||"Unable to generate stickers.");setGeneratedImage(data.imageUrl);setGeneratedImageKey(data.imageKey);setStage("reveal")}catch(error){setGenerationError(error instanceof Error?error.message:"Unable to generate stickers.");setStage("reveal")}};
  const restart=()=>setStage("home");
  const toggleMood=(mood:string)=>setMoods(current=>current.includes(mood)?current.filter(item=>item!==mood):[...current,mood]);
  const openPayment=()=>{setPaymentPlan("one-time");setCheckoutError("");setPaymentStep("email");setPaymentOpen(true)};
    const startCheckout=async()=>{if(paymentPlan==="subscription"){void startSubscription();return}setCheckoutLoading(true);setCheckoutError("");try{const response=await fetch("/api/create-checkout-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,subject,imageKey:generatedImageKey})});const data=await response.json() as {url?:string;error?:string};if(!response.ok||!data.url)throw new Error(data.error||"Unable to start checkout.");window.location.assign(data.url)}catch(error){setCheckoutError(error instanceof Error?error.message:"Unable to start checkout.");setCheckoutLoading(false)}};
  const startSubscription=async(subjectOverride=subject,imageKeyOverride=generatedImageKey)=>{if(!email){setPaymentPlan("subscription");setCheckoutError("");setPaymentStep("email");setPaymentOpen(true);setSubscriptionLoading(false);return}setSubscriptionLoading(true);setCheckoutError("");try{const response=await fetch("/api/create-subscription-session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,subject:subjectOverride,imageKey:imageKeyOverride})});const data=await response.json() as {url?:string;error?:string};if(!response.ok||!data.url)throw new Error(data.error||"Unable to start subscription.");window.location.assign(data.url)}catch(error){setCheckoutError(error instanceof Error?error.message:"Unable to start subscription.");setSubscriptionLoading(false)}};
  const back:Partial<Record<Stage,Stage>>={choose:"home",photos:"choose",details:"photos",mood:"details",theme:"mood",add:"theme",companion:"add",reveal:"theme"};
  return <main className={`shell ${stage}`}><div className="grain"/>{stage!=="confirmation"&&<nav><button className="logo" onClick={restart}>STICKIER<sup>™</sup></button><span>{stage==="home"?"YOUR LIFE, BUT STICKIER":stage==="samples"?"THE SAMPLE STUDIO":product==="pet"?"THE PET STICKER STUDIO":"THE LIFE STICKER STUDIO"}</span><button className="nav-cta" onClick={()=>stage==="home"?setStage("samples"):stage==="samples"?setStage("choose"):restart()}>{stage==="home"?"SEE SAMPLES":stage==="samples"?"CREATE MINE":"EXIT STUDIO"}</button></nav>}

  {stage==="home"&&<section className="split enter"><div className="copy"><h1>Your life.<br/><em>As a sticker sheet.</em></h1><p>We&apos;ll turn you, your favorite person, pet, obsession, and tiny rituals into one ridiculously cute sticker sheet.</p><div className="home-cta"><Button className="red-btn" onClick={()=>setStage("choose")}>MAKE MY SHEET <ArrowRight/></Button></div></div><div className="art"><div className="tag t1">YOUR ERA</div><div className="tag t2">ONE OF ONE</div><Sheet name={name||"Your"} className="tilt"/><div className="burst">10<small>STICKERS</small></div></div></section>}

  {stage==="samples"&&<section className="samples-page enter"><header className="samples-head"><h2>See what gets<br/><em>stuck.</em></h2><p>Every sheet includes ten one-of-one stickers.</p></header><div className="sample-grid clean">{samples.map((sample,i)=><article className="sample-card" key={sample}><div className="sample-sheet"><div><span>STICKIER™</span><small>{sample} / 06</small></div><img src="/sticker-sheet.png" alt={`Sticker sheet sample ${i+1} with ten stickers`}/><footer>10 STICKERS · ONE OF ONE</footer></div></article>)}</div></section>}

  {["choose","photos","details","mood","theme","add","companion"].includes(stage)&&<section className="wizard enter"><aside><div><span>THE STICKER ERA METHOD</span><h2>{product==="pet"?<>Tiny quirks.<br/>Big personality.</>:<>The details<br/>make the era.</>}</h2></div><Sheet name={subject} className="wizard-sheet"/></aside><div className="wizard-main"><div className="wizard-rail">{back[stage]&&<button className="back" onClick={()=>setStage(back[stage]!)}><ArrowLeft/> BACK</button>}<Progress n={currentStep} total={total}/></div>
  {stage==="choose"&&<div className="wizard-content choose-content"><Progress n={1} total={4}/><h3>Who are we turning<br/>into stickers?</h3><div className="choice-grid"><button onClick={()=>start("me")}><i><UserRound/></i><b>Me</b><span>My personality, hobbies &amp; favorite things</span><ArrowRight/></button><button onClick={()=>start("pet")}><i><PawPrint/></i><b>My pet</b><span>Their personality, quirks &amp; favorite things</span><ArrowRight/></button><button onClick={()=>start("partner")}><i><Heart/></i><b>My partner</b><span>Your relationship, rituals &amp; favorite memories</span><ArrowRight/></button><button onClick={()=>start("family")}><i><UsersRound/></i><b>Family &amp; friends</b><span>Your favorite people, moments &amp; inside jokes</span><ArrowRight/></button></div></div>}
  {stage==="photos"&&<div className="wizard-content"><Progress n={2} total={total}/><h3>Add a few photos<br/>of {photoTarget}.</h3><p>Different angles and expressions give your stickers more range. At least one photo is required.</p><UploadBox pet={product==="pet"} target={photoTarget} previews={photos} onChange={f=>load(f,setPhotos)}/><div className="wizard-actions"><span/><Button className="red-btn" disabled={photos.length===0} onClick={()=>setStage("details")}>NEXT <ArrowRight/></Button></div></div>}
  {stage==="details"&&product!=="pet"&&<div className="wizard-content details"><Progress n={3} total={total}/><h3>What belongs in this sticker pack?</h3><label className="request-box"><span>ANY SPECIAL REQUESTS</span><textarea value={specialRequest} onChange={e=>setSpecialRequest(e.target.value)} placeholder="Tell us anything you want included…"/><small>{requestExample} Optional.</small></label><div className="wizard-actions"><span/><Button className="red-btn" onClick={()=>setStage("mood")}>NEXT <ArrowRight/></Button></div></div>}
  {stage==="details"&&product==="pet"&&<div className="wizard-content details pet-form"><Progress n={3} total={total}/><h3>What belongs in this sticker pack?</h3><div className="pet-fields"><label><span>What&apos;s their name?</span><input value={pet.name} onChange={e=>setPet({...pet,name:e.target.value})}/></label><label><span>Type of animal</span><select value={pet.species} onChange={e=>setPet({...pet,species:e.target.value})}><option>Dog</option><option>Cat</option><option>Bird</option><option>Rabbit</option><option>Other</option></select></label></div><label className="request-box"><span>ANY SPECIAL REQUESTS</span><textarea value={specialRequest} onChange={e=>setSpecialRequest(e.target.value)} placeholder="Tell us anything you want included…"/><small>{requestExample} Optional.</small></label><div className="wizard-actions"><span/><Button className="red-btn" onClick={()=>setStage("mood")}>NEXT <ArrowRight/></Button></div></div>}
  {stage==="mood"&&<div className="wizard-content"><Progress n={4} total={total}/><h3>What&apos;s the mood?</h3><div className="mood-options">{moodOptions.map(mood=><button className={moods.includes(mood)?"selected":""} aria-pressed={moods.includes(mood)} key={mood} onClick={()=>toggleMood(mood)}>{mood}{moods.includes(mood)&&<Check/>}</button>)}</div><div className="wizard-actions"><span/><Button className="red-btn" onClick={()=>setStage("theme")}>NEXT <ArrowRight/></Button></div></div>}
  {stage==="theme"&&<div className="wizard-content"><Progress n={5} total={total}/><h3>Choose a theme.</h3><p>We&apos;ll weave it into the colors, props, and tiny details.</p><div className="theme-grid">{[["Classic","—","Classic & neutral"],["Valentine's Day","♥","Sweet & romantic"],["Halloween","◐","Spooky & cute"],["Thanksgiving","🍂","Cozy fall energy"],["Christmas","★","Festive & bright"],["Birthday","✦","Party mode"]].map(([label,icon,copy])=><button className={theme===label?"selected":""} key={label} onClick={()=>setTheme(label)}><i>{icon}</i><b>{label}</b><span>{copy}</span>{theme===label&&<Check/>}</button>)}</div><div className="wizard-actions"><span/><Button className="red-btn" onClick={()=>product==="me"?setStage("add"):generate()}>{product==="me"?<>NEXT <ArrowRight/></>:<>GENERATE <Sparkles/></>}</Button></div></div>}
  {stage==="add"&&<div className="wizard-content"><Progress n={6} total={7}/><div className="eyebrow">YOUR SUPPORTING CAST</div><h3>Anyone else who belongs<br/>on your sheet?</h3><p>You&apos;ll still be the main character.</p><div className="choice-grid three"><button onClick={()=>{setCompanion("pet");setStage("companion")}}><i>🐶</i><b>My pet</b><span>The four-legged co-star</span></button><button onClick={()=>{setCompanion("person");setStage("companion")}}><i>♥</i><b>My person</b><span>A favorite human</span></button><button onClick={()=>{setCompanion("skip");generate()}}><i>→</i><b>Just me</b><span>Skip and generate</span></button></div></div>}
  {stage==="companion"&&<div className="wizard-content"><Progress n={7} total={7}/><div className="eyebrow">ADD YOUR {companion==="pet"?"CO-STAR":"PERSON"}</div><h3>Upload {companion==="pet"?"your pet":"your favorite person"}.</h3><p>One or two clear photos are perfect.</p><UploadBox pet={companion==="pet"} target={companion==="pet"?"your pet":"your favorite person"} previews={companionPhotos} onChange={f=>load(f,setCompanionPhotos)}/><div className="wizard-actions"><button className="skip" onClick={generate}>SKIP</button><Button className="red-btn" onClick={generate}>GENERATE <Sparkles/></Button></div></div>}
  </div></section>}

  {stage==="generating"&&<section className="generate enter"><div className="printer"><div className="printer-top"><span/><span/><span/></div><div className="paper"><GenericStickerSheet/></div><div className="printer-slot"/></div><div className="generate-copy"><b>MAKING YOUR STICKER SHEET</b><h2>{lines[tick]}</h2><div className="progress"><i/></div><small className="generation-estimate">Takes approximately 30–60 seconds</small></div></section>}
  {stage==="reveal"&&<section className="reveal-page enter"><div className="reveal-head"><div><h2>{product==="pet"?`${subject}, as stickers.`:"Your life, as stickers."}</h2><p>Ten digital stickers, ready to download and use anywhere.</p>{generationError&&<p role="alert">{generationError}</p>}</div><div className="reveal-actions"><Button className="red-btn" onClick={openPayment}>PURCHASE STICKERS · $3.99 <ArrowRight/></Button><Button className="subscription-btn" onClick={startSubscription} disabled={subscriptionLoading}>{subscriptionLoading?"OPENING…":"SUBSCRIBE · $9.99 / MONTH"}<ArrowRight/></Button></div></div><div className="reveal-body"><div className="sticker-grid">{positions.map((pos,i)=><div className={`sticker-tile ${i===9?"sticker-tile-last":""}`} key={i}><span>{String(i+1).padStart(2,"0")}</span><div className="sticker-image" style={generatedSlices[i]?{backgroundImage:`url(${generatedSlices[i]})`,backgroundSize:"contain",backgroundPosition:"center",backgroundRepeat:"no-repeat"}:{backgroundImage:`url(${generatedImage||"/sticker-sheet.png"})`,backgroundPosition:pos,backgroundSize:"300% 400%",backgroundRepeat:"no-repeat"}}/><small className="cell-watermark cell-watermark-one" aria-hidden="true">STICKIER · PREVIEW</small><small className="cell-watermark cell-watermark-two" aria-hidden="true">STICKIER · PREVIEW</small><small className="cell-watermark cell-watermark-three" aria-hidden="true">STICKIER · PREVIEW</small></div>)}</div><aside className="full-sheet-preview"><div><span>THE FULL SHEET</span></div><Sheet name={subject} clean src={generatedImage||"/sticker-sheet.png"}/></aside></div></section>}
  {stage==="confirmation"&&<section className="confirmation enter"><div className="check"><Check/></div><div className="eyebrow">PURCHASE COMPLETE</div><h2>Your digital stickers are ready.</h2><p>We sent a copy to <b>{email}</b>. You can also download your sticker sheet now.</p><Sheet name={subject} className="confirmation-sheet" clean src={generatedImage||"/sticker-sheet.png"}/><div className="confirmation-actions"><a className="download-btn" href={checkoutSessionId?`/api/download-stickers?session_id=${encodeURIComponent(checkoutSessionId)}`:"#"} aria-disabled={!checkoutSessionId}><Download/> DOWNLOAD STICKERS</a><Button className="link" onClick={restart}>MAKE ANOTHER <ArrowRight/></Button></div></section>}

  <Dialog open={paymentOpen} onOpenChange={setPaymentOpen}><DialogContent className="payment-modal">{paymentStep==="email"?<><DialogHeader><div className="payment-kicker">DIGITAL STICKER PACK · $3.99</div><DialogTitle>Where should we send your stickers?</DialogTitle><DialogDescription>We&apos;ll email you a copy and also make it available to download immediately after payment.</DialogDescription></DialogHeader><div className="card-fields"><label><span>EMAIL ADDRESS</span><input type="email" required autoFocus value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label></div><Button className="black-btn pay-card" disabled={!/^\S+@\S+\.\S+$/.test(email)} onClick={()=>setPaymentStep("payment")}>CONTINUE TO PAYMENT <ArrowRight/></Button></>:<><DialogHeader><div className="payment-kicker">DIGITAL STICKER PACK · $3.99</div><DialogTitle>Secure checkout.</DialogTitle><DialogDescription>Your stickers will be sent to {email}. Stripe securely handles your payment details.</DialogDescription></DialogHeader>{checkoutError&&<p role="alert">{checkoutError}</p>}<Button className="black-btn pay-card" disabled={checkoutLoading} onClick={startCheckout}>{checkoutLoading?"OPENING CHECKOUT…":"PAY $3.99 WITH STRIPE"} <ArrowRight/></Button><button className="change-email" onClick={()=>setPaymentStep("email")}>CHANGE EMAIL</button><small className="payment-note">Secure digital checkout · No physical shipment</small></>}</DialogContent></Dialog>
  </main>;
}
