import type { generationRequestSchema } from "@/lib/validation";
import type { z } from "zod";

export type GenerationInput = z.infer<typeof generationRequestSchema>;

export function promptFor(input: GenerationInput, hasStyleReference = false): string {
  const details = [
    `Subject: ${input.subject || "the person in the reference photos"}`,
    hasStyleReference
      ? "Style reference: The FINAL provided image is the exact target look. Copy its construction exactly: the same body proportions and head-to-body ratio, the same eye and face construction, the same line weight and ink colour, the same warm painterly cel shading, the same hair and fur texture, the same colour temperature, and the same thick white die-cut treatment. Do not copy that sample's specific person, dog, clothing, costumes, theme, props, poses, composition, or background; derive identity and requested content only from the earlier customer photos and this written request. The subject's age, ethnicity, skin tone, and distinctive features stay the same as the customer photos even though the body proportions change to chibi."
      : "",
    input.product === "pet" && input.species ? `Animal: ${input.species}` : "",
    input.companion && input.companion !== "skip"
      ? `Required companion: a separate ${input.companion === "pet" ? input.species || "pet" : "person"} named ${input.companionName || "the companion"}. Include this companion clearly in multiple stickers. Do not replace or omit the companion.`
      : "",
    input.theme ? `Theme: ${input.theme}` : "",
    input.moods.length ? `Mood: ${input.moods.join(", ")}` : "",
    input.specialRequest ? `Special request: ${input.specialRequest}` : "",
  ].filter(Boolean);

  const petOnly =
    input.product === "pet"
      ? "This is a pet-only pack. The subject is the dog in the reference photos. Every sticker must depict that dog; include no humans, human faces, or human bodies."
      : "";

  const styleDirection =
    "Match this visual direction exactly: warm hand-drawn 2D character illustration in a modern animated-storybook style, the look of a high-end illustrated sticker pack. Bold dark brown-black ink outlines with tapered, confident, varied line weight around every silhouette and interior detail. Warm painterly cel shading with soft airbrushed gradients, rich mid-tone shadows, gentle warm rim light, and dimensional highlights, never flat single-tone fills. Lean into a soft hand-painted Japanese animation feel: gouache and watercolor-like texture within the shading, delicate feathered falloff where light fades into shadow, luminous atmospheric warmth, and a nostalgic storybook tenderness. Hair drawn as thick flowing individually defined strands with glossy specular highlights; animal fur drawn as soft directional tufts with visible individual clumps and a fluffy irregular outer edge. Expressive dark almond-shaped adult eyes with defined irises and crisp catchlights — large enough to read as stickers, but not so oversized that the face looks like a child's. Lashes only if the reference photo shows them; do not add feminine makeup, heavy lashes, or glossy lips to male subjects. A defined adult nose with a small bridge; a visible adult jawline and cheekbones; cheeks that are softly modeled, not puffy or baby-round; only the lightest blush if the reference shows it. Warm, friendly, readable expressions. A warm natural earthy palette with saturated but never neon color. Cozy everyday lifestyle poses and interactions.";

  const proportionRules =
    "Use cute chibi sticker proportions: a large round head that is roughly one third of a standing figure's total height, a compact torso, and shortened but still articulated limbs with rounded hands and feet. This is chibi, not a realistic animated feature: oversized heads, smaller bodies, plump toy-like silhouettes. Do not collapse into extreme super-deformed baby-blobs: keep a readable neck, distinct arms and legs, and hands with fingers. Pets should match the same cute compact scale.";

  const isolationRules =
    "Treat this as a brand-new, standalone request. Only follow details explicitly listed below and visible in the currently provided photos. If a prop, accessory, costume, or style choice is not explicitly requested in this request, do not add it. Never infer carry-over edits from earlier generations (for example, do not add sunglasses unless this request asks for sunglasses).";

  const spacingRules =
    "The canvas is a portrait sheet with a 3:4 width-to-height ratio. Use an invisible 3-column by 4-row grid covering it, which makes every cell an equal square. Cell boundaries are at x=33.33%, x=66.67%, y=25%, y=50%, and y=75%. Put exactly one sticker in each of these cells: row 1 columns 1-3, row 2 columns 1-3, row 3 columns 1-3, and row 4 column 2 only. Leave row 4 columns 1 and 3 completely empty pure white. Each sticker, including every subject, prop, white die-cut outline, and shadow, must fit within the centered inner 76% of its own square cell. The outer margin of every cell must remain completely blank pure white, creating uninterrupted vertical and horizontal gutters across the entire canvas. A sticker may never enter another cell, share a cell, span two cells, overlap a grid boundary, or place any fragment in a neighboring cell. There must be exactly one self-contained sticker per occupied square and zero stray fragments. Scale a pose down until its whole silhouette fits; never crop a head, face, hair, limb, pet, prop, outline, or shadow.";

  return `Create exactly one complete premium die-cut sticker sheet image, not multiple output images. Arrange exactly ten separate sticker illustrations in the specified 3-column by 4-row grid. All ten stickers must depict the same recognizable subject or subjects consistently across the sheet, with matching facial identity, hair, skin tone, and distinctive features; only pose, expression, clothing, and props should vary. ${styleDirection} ${proportionRules} Avoid generic corporate vector art, thick geometric shapes, flat icon art, clip art, emoji art, plastic 3D rendering, photorealism, coloring-book drawings, and rough sketches. Apply a tasteful flattering idealization while preserving identity, a subtle lift of roughly ten to fifteen percent rather than a transformation: more harmonious and balanced adult facial proportions, bright well-shaped eyes, clear even luminous skin, refined well-groomed hair, softly defined flattering adult features, a warm healthy glow, a relaxed confident posture, and polished camera-ready styling. Keep the person unmistakably recognizable and do not change their age, ethnicity, skin tone, body type, hair identity, or distinctive features. Chibi changes body proportions only — keep the current head-to-body scale. Age the face to match the reference photos: a young adult, slightly more mature than a cute-sticker default, with adult facial structure, an adult jawline, adult eye placement, and an adult face-to-forehead ratio. Do not de-age them into a child, tween, high-school, or teen-idol look. Preserve the subject's gender presentation exactly as shown in the reference photos: keep masculine jawlines, brow ridges, and facial hair if present; do not soften features into a feminine or androgynous idealization. Use only the current request details and the currently provided reference photos. ${isolationRules} ${spacingRules} ${petOnly} Preserve each required subject's recognizable features and include every required subject clearly. Give every sticker a bold, smooth, evenly thick white die-cut border that follows the silhouette. The entire canvas outside the stickers must be solid pure white (#FFFFFF). Absolutely no cream, tan, beige, gray, or black background pixels anywhere: no horizontal bands at the top, between rows, or at the bottom; no vertical bands; no paper texture, paper borders, frames, headers, footers, dividers, panels, strips, or background shapes; no shadows outside the sticker die-cuts, watermark, unrequested people, or readable text inside the artwork. Render at maximum detail and sharpness: crisp unbroken outlines, clean edges, and no blur, noise, banding, or compression artifacts, because this sheet will be printed. Before finalizing, verify all ten occupied squares contain exactly one complete sticker and no square contains any piece of a neighboring sticker.\n\n${details.join("\n")}`;
}
